name: flutter_microbank
description: Minimal Flutter app for AI MicroBank
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6

flutter:
  uses-material-design: true
